### ISSUE TITLE
Reader closure problem

### ISSUE THREAD

**Issue by RiccardoLincetto** [BlueMirrors/vidsz#6]
I think there might be a problem on closing the video reader. This is the situation:
```
from vidsz.opencv import Reader

reader = Reader("static/countdown.mp4")

while reader.is_open():
    ...
    if condition:
        reader.release()
```
Since `reader.release()` does the following:
```
def release(self) -> None:
    """Release Resources
    """
    if self._video_stream is not None:
        self._video_stream.release()
        self._video_stream = None
```
on the following iteration, reader is None and thus does not have a function `isOpened()`.
Thus it raises the error: **'NoneType' object has no attribute 'isOpened'**.

I tried to check the code if there could be a better way of closing the Reader but I couldn't find one.

What about adding a condition to `reader.is_open()`, checking that `reader._video_stream is not None and ...`?

**Comment by shivamswarnkar** [comment]
@RiccardoLincetto  Thanks for checking out our repo. And yeah, that's a very good catch.

Initially, I was thinking of adding a restart option in the reader which can be useful for working with streams (that's why I left the setting to None in the release method). But we can work on that in the future separately, for now, I agree with your comments and proposed fix.

I'll review your PR and merge it soon, and thanks again for contributing, we really appreciate it.
